# Generated by Django 5.2.2 on 2025-06-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacherprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_pics/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='qualification',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
