# Generated by Django 5.2.2 on 2025-06-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacherprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
