# Generated by Django 5.2.2 on 2025-07-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_teacherprofile_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
