# Generated by Django 5.2.2 on 2025-08-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='parent_pics/'),
        ),
    ]
