# Generated by Django 5.2.2 on 2025-08-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_fee_delete_feerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
