# Generated by Django 5.2.2 on 2025-08-02 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_fee_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='date_generated',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='fee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
