# Generated by Django 5.2.2 on 2025-06-08 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('teachers', '0003_alter_teacherprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='course',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='date',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='marks_obtained',
        ),
        migrations.AddField(
            model_name='examresult',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='examresult',
            name='obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam_name',
            field=models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final'), ('assignment', 'Assignment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_marks',
            field=models.PositiveIntegerField(),
        ),
    ]
