# Generated by Django 5.2.2 on 2025-06-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_examresult_course_remove_examresult_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
