# Generated by Django 5.2.2 on 2025-07-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_exam_subject'),
        ('students', '0003_alter_studentprofile_courses_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'subject', 'exam_name')},
        ),
    ]
